apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: genosentinel
type: Opaque
data:
  # root password: admin (base64 encoded)
  mysql-root-password: YWRtaW4=
  # user: genouser (base64 encoded)
  mysql-user: Z2Vub3VzZXI=
  # password: genopass123 (base64 encoded)
  mysql-password: Z2Vub3Bhc3MxMjM=

